# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        /:title

# Setup
title:             varun vachhar
tagline:           finder of new ways to confuse myself
url:               http://blog.lambdafunction.ca
paginate:          3
excerpt_separator: <!--more-->
baseurl:					 /
exclude: 					 ['node_modules']
author:
  name:            Varun Vachhar
  url:             https://twitter.com/winkerVSbecks
  email:           varunvachhar@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/winkerVSbecks/le-blog
